image: nmichalov/veracode-tools

stages:
    - build
    - scan

package:
    stage: build
    script:
        - mvn package
    artifacts:
        paths:
            - target/verademo.war
    
veracode-policy-scan:
    stage: scan
    only:
        - schedules
        - master
    script:
        - java -jar /veracode/veracode-wrapper.jar -vid ${API_ID} -vkey ${API_KEY}
          -action uploadandscan -appname "${PROJECT_NAME}" -autoscan true -createprofile false
          -version "job ${CI_JOB_ID} in pipeline ${CI_PIPELINE_ID}" -filepath target/verademo.war
