image: nmichalov/veracode-tools

stages:
    - build
    # - policy
    - devops
    - sca

package:
    stage: build
    script:
        - mvn package
    artifacts:
        paths:
            - target/verademo.war
    
veracode-scan:
    # stage: policy
    # only:
    #     - schedules
    #     - master
    # script:
    #     - java -jar /veracode/veracode-wrapper.jar -vid ${API_ID} -vkey ${API_KEY}
    #       -action uploadandscan -appname "${PROJECT_NAME}" -autoscan true -createprofile false
    #       -version "job ${CI_JOB_ID} in pipeline ${CI_PIPELINE_ID}" -filepath target/verademo.war
    stage: devops
    only:
       - schedules
       - master
    script:
       - curl -O https://downloads.veracode.com/securityscan/devops-scanner-java-LATEST.zip
       - unzip -o devops-scanner-java-LATEST.zip devops-scanner-java.jar
       - java -jar devops-scanner-java.jar \
                    --api_id ${API_ID} \
                    --api_secret_key ${API_KEY} \
                    --project_name ${PROJECT_NAME} \
                    -j target/verademo.war 
    stage: sca
    only:
        - schedules
        - master
    script:
        - curl -sSL https://download.sourceclear.com/ci.sh | sh
