image: nmichalov/veracode-tools

stages:
    - build
    - scan

package:
    stage: build
    script:
        - mvn package
    artifacts:
        paths:
            - target/verademo.war
    
veracode-policy-scan:
    stage: scan
    only:
        - schedules
        - master
    before_script:
        - wget -q -O veracode-wrapper.jar https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/${VERACODE_WRAPPER_VERSION}/vosp-api-wrappers-java-${VERACODE_WRAPPER_VERSION}.jar
    script:
        - java -jar veracode-wrapper.jar -vid ${API_ID} -vkey ${API_KEY}
          -action UploadAndScan -appname "${PROJECT_NAME}" -autoscan true
          -filepath target/ -version "job ${CI_JOB_ID} in pipeline ${CI_PIPELINE_ID}"