# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  name: Azure Pipelines
  demands: maven
​
  steps:
- script: 'wget https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip'
  displayName: 'Command Line Script'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
​
- task: ExtractFiles@1
  displayName: 'Extract files '
  inputs:
    archiveFilePatterns: 'pipeline-scan-LATEST.zip'
    destinationFolder: '$(System.DefaultWorkingDirectory)'
    cleanDestinationFolder: false
​
- task: Maven@3
  displayName: 'Maven pom.xml'
  inputs:
    mavenPomFile: '$(Parameters.mavenPOMFile)'
​
- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*.jar'
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
​
- script: 'java -jar $(System.DefaultWorkingDirectory)/pipeline-scan.jar --fail_on_severity="Very High, High, Medium" -vid $(VERACODE_API_ID) -vkey $(VERACODE_API_KEY) -f  $(system.defaultworkingdirectory)/*.jar'
  displayName: 'Command Line Script'
​
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'