# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml

- name: Veracode Upload And Scan
  # You may pin to the exact commit or the version.
  # uses: veracode/veracode-uploadandscan-action@c5e63c8383debb26a0d48250eab75d94327635ba
  uses: veracode/veracode-uploadandscan-action@0.2.1
  with:
    # appname
    appname: 'Build System Demo Application'
    # createprofile
    createprofile: # default is true
    # filepath
    filepath: verademo.war
    # version
    version: ${{ github.run_id }}
    # vid
    vid: 08ddce4e64fb9a6a2cf0d2569e304c4a
    # vkey
    vkey: 1b0d280b5d691463ade81c4d90ff6c93a4f0edefcc9f84a7deebc9f57050b27c45016bba5c63669d10ee79d9c5da84144674e2ebbab979e72421fa2b564ab0ab
    # true or flase
    createsandbox: true
    # name of the sandbox
    sandboxname: 'GitHub-Build'
    # wait X minutes for the scan to complete
    scantimeout: # optional
    # modules to exclude from module selection
    exclude: # optional
    # modules to include in module selection
    include: # optional
    # business criticality - policy selection
    criticality: # optional
    # filename pattern
    pattern: # optional
    # replacement
    replacement: # optional
    # replacement
    sandboxid: # optional
    # All top level modules
    scanallnonfataltoplevelmodules: # optional
    # platform selected modules
    selected: # optional
    # selected modules like from previous scan
    selectedpreviously: # optional
    # teams
    teams: # optional
    # teams
    toplevel: # optional
